/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import conexion.Conexion;
import inmo_data.InquilinoData;
import java.sql.Connection;
import javax.swing.JOptionPane;
import t_final_inmobiliaria_g5.Inquilino;

/**
 *
 * @author mseba
 */
public class Vista_FormInquilino extends javax.swing.JInternalFrame {
     Conexion conexion;
    /**
     * Creates new form vistas_Form
     */
    public Vista_FormInquilino(Conexion conexion) {
        initComponents();
        this.conexion = conexion;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        JTtrabajo = new javax.swing.JTextField();
        jLbNombre4 = new javax.swing.JLabel();
        JTdni = new javax.swing.JTextField();
        JTnombre = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLbCuit4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        JTcuit_dni = new javax.swing.JTextField();
        jLbDniGarante = new javax.swing.JLabel();
        jLbTelefono4 = new javax.swing.JLabel();
        JTdni_garante = new javax.swing.JTextField();
        jLbApellidoGarante = new javax.swing.JLabel();
        JTtelefono = new javax.swing.JTextField();
        JTnombre_garante = new javax.swing.JTextField();
        jLbNombreGarante = new javax.swing.JLabel();
        jLbTrabajo4 = new javax.swing.JLabel();
        JTapellido_garante = new javax.swing.JTextField();
        jLbApellido4 = new javax.swing.JLabel();
        jLbDni4 = new javax.swing.JLabel();
        JTapellido = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        JTcuit_postdni = new javax.swing.JTextField();
        JTcuit_predni = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();

        JTtrabajo.setBackground(new java.awt.Color(204, 204, 204));
        JTtrabajo.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLbNombre4.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLbNombre4.setText("Nombre:");

        JTdni.setBackground(new java.awt.Color(204, 204, 204));
        JTdni.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTdni.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                JTdniFocusLost(evt);
            }
        });
        JTdni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTdniActionPerformed(evt);
            }
        });

        JTnombre.setBackground(new java.awt.Color(204, 204, 204));
        JTnombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLbCuit4.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLbCuit4.setText("Cuit:");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("GARANTE");

        JTcuit_dni.setBackground(new java.awt.Color(204, 204, 204));
        JTcuit_dni.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTcuit_dni.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                JTcuit_dniFocusLost(evt);
            }
        });

        jLbDniGarante.setText("DNI:");

        jLbTelefono4.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLbTelefono4.setText("Telefono:");

        JTdni_garante.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                JTdni_garanteFocusLost(evt);
            }
        });

        jLbApellidoGarante.setText("Apellido: ");

        JTtelefono.setBackground(new java.awt.Color(204, 204, 204));
        JTtelefono.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLbNombreGarante.setText("Nombre:");

        jLbTrabajo4.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLbTrabajo4.setText("Trabajo:");

        jLbApellido4.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLbApellido4.setText("Apellido: ");

        jLbDni4.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLbDni4.setText("DNI:");

        JTapellido.setBackground(new java.awt.Color(204, 204, 204));
        JTapellido.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jButton1.setText("GUARDAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("SALIR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        JTcuit_postdni.setBackground(new java.awt.Color(204, 204, 204));
        JTcuit_postdni.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTcuit_postdni.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                JTcuit_postdniFocusLost(evt);
            }
        });
        JTcuit_postdni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTcuit_postdniActionPerformed(evt);
            }
        });

        JTcuit_predni.setBackground(new java.awt.Color(204, 204, 204));
        JTcuit_predni.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTcuit_predni.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                JTcuit_predniFocusLost(evt);
            }
        });
        JTcuit_predni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTcuit_predniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLbApellido4)
                            .addComponent(jLbNombre4)
                            .addComponent(jLbCuit4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLbTelefono4, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(jLbTrabajo4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLbDni4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(69, 69, 69)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(JTtrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTdni, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTapellido, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTtelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(JTcuit_predni, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(JTcuit_dni, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(JTcuit_postdni, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLbApellidoGarante, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLbDniGarante, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLbNombreGarante)))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JTapellido_garante, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTdni_garante, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTnombre_garante, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbDni4)
                    .addComponent(JTdni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbApellido4)
                    .addComponent(JTapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JTnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLbNombre4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbCuit4)
                    .addComponent(JTcuit_postdni, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTcuit_predni, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTcuit_dni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbTelefono4)
                    .addComponent(JTtelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTtrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLbTrabajo4))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTdni_garante, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLbDniGarante))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTnombre_garante, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLbNombreGarante))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbApellidoGarante)
                    .addComponent(JTapellido_garante, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jDesktopPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Cargar Cliente", jDesktopPane1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 634, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 497, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Modificar Cliente", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 634, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 497, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Buscar Cliente", jPanel3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 634, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 497, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Borrar Cliente", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 639, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        Inquilino inqui = new Inquilino();
        inqui.setApellido(JTapellido.getText());
        inqui.setApellidoGarante(JTapellido_garante.getText());
        inqui.setCuit(Integer.parseInt(JTcuit_dni.getText()));
        inqui.setDni(Integer.parseInt(JTdni.getText()));
        inqui.setDniGarante(Integer.parseInt(JTdni_garante.getText()));
        inqui.setNombre(JTnombre.getText());
        inqui.setNombreGarante(JTnombre_garante.getText());
        inqui.setTelefono(Long.parseLong(JTtelefono.getText()));
        inqui.setTrabajo(JTtrabajo.getText());
        
        InquilinoData iData = new InquilinoData(conexion);  
        iData.agregarInquilino(inqui);
        


// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void JTcuit_predniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTcuit_predniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTcuit_predniActionPerformed

    private void JTdniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTdniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTdniActionPerformed

    private void JTdniFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTdniFocusLost
            if(JTdni.getText().length()==0){
                JOptionPane.showMessageDialog(this, "DNI no puede quedar vacio");
                JTdni.requestFocus();
            }
            else{
                try {
                    int prueba = Integer.parseInt(JTdni.getText());
                    JTcuit_dni.setText(""+prueba);
                } catch (NumberFormatException ex) {
                    JOptionPane.showMessageDialog(this, "DNI debe ser un numero");
                    JTdni.requestFocus();
                }
            }
    }//GEN-LAST:event_JTdniFocusLost

    private void JTcuit_postdniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTcuit_postdniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTcuit_postdniActionPerformed

    private void JTcuit_dniFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTcuit_dniFocusLost
                   if(JTcuit_dni.getText().length()==0){
                JOptionPane.showMessageDialog(this, "Ningun campo del CUIT no puede quedar vacio");
                JTcuit_dni.requestFocus();
            }
            else{
                try {
                    int prueba = Integer.parseInt(JTcuit_dni.getText());
                    JTdni.setText(""+prueba);
                } catch (NumberFormatException ex) {
                    JOptionPane.showMessageDialog(this, "Los campos de CUIT deben ser numeros");
                    
                    JTcuit_dni.requestFocus();
                }
            }  // TODO add your handling code here:
    }//GEN-LAST:event_JTcuit_dniFocusLost

    private void JTcuit_predniFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTcuit_predniFocusLost
                    if(JTcuit_predni.getText().length()==0){
                JOptionPane.showMessageDialog(this, "Ningun campo del CUIT no puede quedar vacio");
                JTcuit_predni.requestFocus();
            }
            else{
                try {
                    int prueba = Integer.parseInt(JTcuit_predni.getText());
                    
                } catch (NumberFormatException ex) {
                    JOptionPane.showMessageDialog(this, "Los campos de CUIT deben ser numeros");
                    JTcuit_predni.requestFocus();
                }
            }         // TODO add your handling code here:
    }//GEN-LAST:event_JTcuit_predniFocusLost

    private void JTcuit_postdniFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTcuit_postdniFocusLost
                       if(JTcuit_postdni.getText().length()==0){
                JOptionPane.showMessageDialog(this, "Ningun campo del CUIT no puede quedar vacio");
                JTcuit_postdni.requestFocus();
            }
            else{
                try {
                    int prueba = Integer.parseInt(JTcuit_postdni.getText());
                    
                } catch (NumberFormatException ex) {
                    JOptionPane.showMessageDialog(this, "Los campos de CUIT deben ser numeros");
                    JTcuit_postdni.requestFocus();
                }
            }           // TODO add your handling code here:
    }//GEN-LAST:event_JTcuit_postdniFocusLost

    private void JTdni_garanteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTdni_garanteFocusLost
        
                  if( JTdni_garante.getText().length()==0){
                JOptionPane.showMessageDialog(this, "El dni del garante no puede quedar vacio");
                 JTdni_garante.requestFocus();
            }
            else{
                try {
                    int prueba = Integer.parseInt( JTdni_garante.getText());
                   
                } catch (NumberFormatException ex) {
                    JOptionPane.showMessageDialog(this, "Los campos de DNI deben ser numeros");
                     JTdni_garante.requestFocus();
                }
            } 
        // TODO add your handling code here:
    }//GEN-LAST:event_JTdni_garanteFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JTapellido;
    private javax.swing.JTextField JTapellido_garante;
    private javax.swing.JTextField JTcuit_dni;
    private javax.swing.JTextField JTcuit_postdni;
    private javax.swing.JTextField JTcuit_predni;
    private javax.swing.JTextField JTdni;
    private javax.swing.JTextField JTdni_garante;
    private javax.swing.JTextField JTnombre;
    private javax.swing.JTextField JTnombre_garante;
    private javax.swing.JTextField JTtelefono;
    private javax.swing.JTextField JTtrabajo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLbApellido4;
    private javax.swing.JLabel jLbApellidoGarante;
    private javax.swing.JLabel jLbCuit4;
    private javax.swing.JLabel jLbDni4;
    private javax.swing.JLabel jLbDniGarante;
    private javax.swing.JLabel jLbNombre4;
    private javax.swing.JLabel jLbNombreGarante;
    private javax.swing.JLabel jLbTelefono4;
    private javax.swing.JLabel jLbTrabajo4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
