/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Chunk;
import conexion.Conexion;
import inmo_data.ContratoAlquilerData;
import inmo_data.InquilinoData;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.Comparator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import t_final_inmobiliaria_g5.ContratoAlquiler;
import t_final_inmobiliaria_g5.Inquilino;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileOutputStream;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import java.awt.Color;
import java.awt.Font;
import java.sql.SQLException;

/**
 *
 * @author mseba
 */
public class Vista_FormInquilino extends javax.swing.JInternalFrame {
     private DefaultTableModel modelo;
     
     Conexion conexion;
     private InquilinoData inquilinoData = null;
     private ArrayList<Inquilino> listaInquilinos;
     private ArrayList<ContratoAlquiler>listaContratos;
     private ContratoAlquilerData contratoAlquilerData;
    /**
     * Creates new form vistas_Form
     */
    public Vista_FormInquilino(Conexion conexion) {
        initComponents();
         modelo = new DefaultTableModel();
        this.conexion = conexion;
        this.inquilinoData = new InquilinoData(conexion);
        listaInquilinos = (ArrayList)inquilinoData.listaTodosInquilinos();
        
         contratoAlquilerData = new ContratoAlquilerData(conexion);
         listaContratos = (ArrayList)contratoAlquilerData.mostrarContratos();
       
        cargarInquilinos();
        //llenarCombo();
        armarCabecera();
        cargaDatos();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        JTtrabajo = new javax.swing.JTextField();
        jLbNombre4 = new javax.swing.JLabel();
        JTdni = new javax.swing.JTextField();
        JTnombre = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLbCuit4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        JTcuit_dni = new javax.swing.JTextField();
        jLbDniGarante = new javax.swing.JLabel();
        jLbTelefono4 = new javax.swing.JLabel();
        JTdni_garante = new javax.swing.JTextField();
        jLbApellidoGarante = new javax.swing.JLabel();
        JTtelefono = new javax.swing.JTextField();
        JTnombre_garante = new javax.swing.JTextField();
        jLbNombreGarante = new javax.swing.JLabel();
        jLbTrabajo4 = new javax.swing.JLabel();
        JTapellido_garante = new javax.swing.JTextField();
        jLbApellido4 = new javax.swing.JLabel();
        jLbDni4 = new javax.swing.JLabel();
        JTapellido = new javax.swing.JTextField();
        jBGuardar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jChBActivo = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jLbDni5 = new javax.swing.JLabel();
        JTdniModifcar = new javax.swing.JTextField();
        JTapellidoModificar = new javax.swing.JTextField();
        jLbApellido5 = new javax.swing.JLabel();
        jLbNombre5 = new javax.swing.JLabel();
        JTnombreModificar = new javax.swing.JTextField();
        jLbCuit5 = new javax.swing.JLabel();
        JTcuit_dniModificar = new javax.swing.JTextField();
        JTtelefonoModificar = new javax.swing.JTextField();
        jLbTelefono5 = new javax.swing.JLabel();
        jLbTrabajo5 = new javax.swing.JLabel();
        JTtrabajoModificar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLbDniGarante1 = new javax.swing.JLabel();
        jLbNombreGarante1 = new javax.swing.JLabel();
        jLbApellidoGarante1 = new javax.swing.JLabel();
        JTapellido_garanteModificar = new javax.swing.JTextField();
        JTnombre_garanteModificar = new javax.swing.JTextField();
        JTdni_garanteModificar = new javax.swing.JTextField();
        jbActualizar = new javax.swing.JButton();
        jbSalirModificar = new javax.swing.JButton();
        jbBuscarModifica = new javax.swing.JButton();
        jbLimpiarModificar = new javax.swing.JButton();
        jTIdModificar = new javax.swing.JTextField();
        jbBorrarModificar = new javax.swing.JButton();
        jChBActivoM = new javax.swing.JCheckBox();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jCBInquilino = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablaProp = new javax.swing.JTable();
        jBImprimir = new javax.swing.JButton();
        jbSalirListar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Clientes");

        JTtrabajo.setBackground(new java.awt.Color(204, 204, 204));
        JTtrabajo.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLbNombre4.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLbNombre4.setText("Nombre:");

        JTdni.setBackground(new java.awt.Color(204, 204, 204));
        JTdni.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTdni.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                JTdniFocusLost(evt);
            }
        });
        JTdni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTdniActionPerformed(evt);
            }
        });

        JTnombre.setBackground(new java.awt.Color(204, 204, 204));
        JTnombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLbCuit4.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLbCuit4.setText("Cuit:");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("GARANTE");

        JTcuit_dni.setBackground(new java.awt.Color(204, 204, 204));
        JTcuit_dni.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTcuit_dni.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                JTcuit_dniFocusLost(evt);
            }
        });

        jLbDniGarante.setText("DNI:");

        jLbTelefono4.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLbTelefono4.setText("Telefono:");

        JTdni_garante.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                JTdni_garanteFocusLost(evt);
            }
        });
        JTdni_garante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTdni_garanteActionPerformed(evt);
            }
        });

        jLbApellidoGarante.setText("Apellido: ");

        JTtelefono.setBackground(new java.awt.Color(204, 204, 204));
        JTtelefono.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTtelefono.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                JTtelefonoFocusLost(evt);
            }
        });

        jLbNombreGarante.setText("Nombre:");

        jLbTrabajo4.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLbTrabajo4.setText("Trabajo:");

        jLbApellido4.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLbApellido4.setText("Apellido: ");

        jLbDni4.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLbDni4.setText("DNI:");

        JTapellido.setBackground(new java.awt.Color(204, 204, 204));
        JTapellido.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jBGuardar.setText("GUARDAR");
        jBGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarActionPerformed(evt);
            }
        });

        jButton2.setText("SALIR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jChBActivo.setSelected(true);
        jChBActivo.setText("Activo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 48, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLbApellido4)
                            .addComponent(jLbNombre4)
                            .addComponent(jLbCuit4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLbTelefono4, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(jLbTrabajo4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLbDni4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(69, 69, 69)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JTcuit_dni)
                            .addComponent(JTtrabajo, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                            .addComponent(JTdni, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                            .addComponent(JTapellido, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                            .addComponent(JTnombre, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                            .addComponent(JTtelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE))
                        .addGap(35, 35, 35)
                        .addComponent(jChBActivo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(jBGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLbApellidoGarante, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLbDniGarante, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLbNombreGarante)))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JTapellido_garante, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTdni_garante, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTnombre_garante, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbDni4)
                    .addComponent(JTdni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jChBActivo))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbApellido4)
                    .addComponent(JTapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JTnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLbNombre4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLbCuit4)
                    .addComponent(JTcuit_dni, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbTelefono4)
                    .addComponent(JTtelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTtrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLbTrabajo4))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTdni_garante, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLbDniGarante))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTnombre_garante, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLbNombreGarante))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbApellidoGarante)
                    .addComponent(JTapellido_garante, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jDesktopPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Cargar Cliente", jDesktopPane1);

        jLbDni5.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLbDni5.setText("DNI:");

        JTdniModifcar.setBackground(new java.awt.Color(204, 204, 204));
        JTdniModifcar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTdniModifcar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                JTdniModifcarFocusLost(evt);
            }
        });
        JTdniModifcar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTdniModifcarActionPerformed(evt);
            }
        });

        JTapellidoModificar.setBackground(new java.awt.Color(204, 204, 204));
        JTapellidoModificar.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLbApellido5.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLbApellido5.setText("Apellido: ");

        jLbNombre5.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLbNombre5.setText("Nombre:");

        JTnombreModificar.setBackground(new java.awt.Color(204, 204, 204));
        JTnombreModificar.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLbCuit5.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLbCuit5.setText("Cuit:");

        JTcuit_dniModificar.setBackground(new java.awt.Color(204, 204, 204));
        JTcuit_dniModificar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTcuit_dniModificar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                JTcuit_dniModificarFocusLost(evt);
            }
        });

        JTtelefonoModificar.setBackground(new java.awt.Color(204, 204, 204));
        JTtelefonoModificar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTtelefonoModificar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                JTtelefonoModificarFocusLost(evt);
            }
        });

        jLbTelefono5.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLbTelefono5.setText("Telefono:");

        jLbTrabajo5.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLbTrabajo5.setText("Trabajo:");

        JTtrabajoModificar.setBackground(new java.awt.Color(204, 204, 204));
        JTtrabajoModificar.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("GARANTE");

        jLbDniGarante1.setText("DNI:");

        jLbNombreGarante1.setText("Nombre:");

        jLbApellidoGarante1.setText("Apellido: ");

        JTdni_garanteModificar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                JTdni_garanteModificarFocusLost(evt);
            }
        });

        jbActualizar.setText("ACTUALIZAR");
        jbActualizar.setEnabled(false);
        jbActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbActualizarActionPerformed(evt);
            }
        });

        jbSalirModificar.setText("SALIR");
        jbSalirModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirModificarActionPerformed(evt);
            }
        });

        jbBuscarModifica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/search_find_lupa_21889.png"))); // NOI18N
        jbBuscarModifica.setToolTipText("Buscar");
        jbBuscarModifica.setBorder(null);
        jbBuscarModifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarModificaActionPerformed(evt);
            }
        });

        jbLimpiarModificar.setText("LIMPIAR CAMPOS");
        jbLimpiarModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimpiarModificarActionPerformed(evt);
            }
        });

        jTIdModificar.setToolTipText("Cód Int");

        jbBorrarModificar.setText("BORRAR");
        jbBorrarModificar.setEnabled(false);
        jbBorrarModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBorrarModificarActionPerformed(evt);
            }
        });

        jChBActivoM.setText("Activo");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTIdModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jbActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbLimpiarModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbBorrarModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jbSalirModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLbApellidoGarante1)
                                    .addComponent(jLbNombreGarante1)
                                    .addComponent(jLbDniGarante1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(42, 42, 42)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JTapellido_garanteModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JTdni_garanteModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JTnombre_garanteModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLbApellido5)
                                    .addComponent(jLbNombre5)
                                    .addComponent(jLbCuit5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLbTelefono5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLbTrabajo5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLbDni5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(69, 69, 69)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jChBActivoM)
                                    .addComponent(JTtrabajoModificar, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                                    .addComponent(JTdniModifcar)
                                    .addComponent(JTapellidoModificar)
                                    .addComponent(JTnombreModificar)
                                    .addComponent(JTtelefonoModificar)
                                    .addComponent(JTcuit_dniModificar))))
                        .addGap(18, 18, 18)
                        .addComponent(jbBuscarModifica, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JTdniModifcar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLbDni5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLbApellido5)
                            .addComponent(JTapellidoModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(JTnombreModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLbNombre5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLbCuit5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JTcuit_dniModificar))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLbTelefono5)
                            .addComponent(JTtelefonoModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLbTrabajo5)
                            .addComponent(JTtrabajoModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addComponent(jChBActivoM)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JTdni_garanteModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLbDniGarante1))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(JTnombre_garanteModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLbNombreGarante1))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JTapellido_garanteModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLbApellidoGarante1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbLimpiarModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbSalirModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbBorrarModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jbBuscarModifica, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(203, 203, 203)
                        .addComponent(jTIdModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jTabbedPane1.addTab("Modificar Cliente", jPanel2);

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        jLabel4.setText("Cliente");

        jCBInquilino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBInquilinoActionPerformed(evt);
            }
        });

        jTablaProp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTablaProp);

        jBImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Quickprinting_printing_6313.png"))); // NOI18N
        jBImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBImprimirActionPerformed(evt);
            }
        });

        jbSalirListar.setText("SALIR");
        jbSalirListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirListarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBImprimir, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                    .addComponent(jbSalirListar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCBInquilino, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCBInquilino, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jBImprimir)
                        .addGap(104, 104, 104)
                        .addComponent(jbSalirListar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Lista de Propiedas", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSalirListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirListarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jbSalirListarActionPerformed

    private void jBImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBImprimirActionPerformed
        // TODO add your handling code here:
        Inquilino inq =(Inquilino)jCBInquilino.getSelectedItem();
        Document documento = new Document();

        try {
            String ruta = System.getProperty("user.home");
            PdfWriter.getInstance(documento, new FileOutputStream(ruta + "/Desktop/" + inq.getNombre().trim()+".pdf"));

            com.itextpdf.text.Image header = com.itextpdf.text.Image.getInstance("src/image/BannerPDF.jpg");
            header.scaleToFit(650,1000);
            header.setAlignment(Chunk.ALIGN_CENTER);

            Paragraph parrafo = new Paragraph();
            parrafo.setAlignment(Paragraph.ALIGN_CENTER);
            parrafo.add("información Del Cliente. \n \n");
            parrafo.setFont(FontFactory.getFont("Tahoma", 14, Font.BOLD, BaseColor.DARK_GRAY));

            documento.open();
            documento.add(header);
            documento.add(parrafo);

            PdfPTable tablaCliente = new PdfPTable(4);
            tablaCliente.addCell("CodigoInterno");
            tablaCliente.addCell("Nombre");
            tablaCliente.addCell("Apellido");
            tablaCliente.addCell("Dni");

            tablaCliente.addCell(inq.getIdInquilino()+"");
            tablaCliente.addCell(inq.getNombre());
            tablaCliente.addCell(inq.getApellido());
            tablaCliente.addCell(inq.getDni()+"");
            documento.add(tablaCliente);

            Paragraph parrafo2 = new Paragraph();
            parrafo2.setAlignment(Paragraph.ALIGN_CENTER);
            parrafo2.add("\n \n Propiedades Alquiladas \n\n");
            parrafo2.setFont(FontFactory.getFont("Tahoma",14,Font.BOLD, BaseColor.DARK_GRAY));

            documento.add(parrafo2);

            PdfPTable tablaPropiedades = new PdfPTable(4);
            tablaPropiedades.addCell("codContrato");
            tablaPropiedades.addCell("idPropiedad");
            tablaPropiedades.addCell("Caracteristica");
            tablaPropiedades.addCell("Dirección");

            for(ContratoAlquiler p : listaContratos){
                //System.out.println("ver contrato id Inquilno"+p.toString());//chequeo de datos
                if(p.getInquilino().getIdInquilino() == inq.getIdInquilino()){

                    tablaPropiedades.addCell(p.getCodContrato());
                    tablaPropiedades.addCell(p.getPropiedad().getIdPropiedad()+"");
                    tablaPropiedades.addCell(p.getPropiedad().getTipo());
                    tablaPropiedades.addCell(p.getPropiedad().getDireccion());
                }
            }

            documento.add(tablaPropiedades);
            JOptionPane.showMessageDialog(this,"El documento se encuentra en Escritorio");
            documento.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"Error al imprimir el documeto");
        }

    }//GEN-LAST:event_jBImprimirActionPerformed

    private void jCBInquilinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBInquilinoActionPerformed
        borraFilasTabla();
        cargaDatos();
    }//GEN-LAST:event_jCBInquilinoActionPerformed

    private void jbBorrarModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBorrarModificarActionPerformed
        // TODO add your handling code here:
        int id =-1;

        try {
            id = Integer.parseInt(jTIdModificar.getText());
            InquilinoData inqdata = new InquilinoData(conexion);
            inqdata.bajaInquilino(id);
            limpiarCamposModificar();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"Error al borrar");
        }

    }//GEN-LAST:event_jbBorrarModificarActionPerformed

    private void jbLimpiarModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimpiarModificarActionPerformed
        // TODO add your handling code here:
        limpiarCamposModificar();
        jbActualizar.setEnabled(false);
         jbBorrarModificar.setEnabled(false);
    }//GEN-LAST:event_jbLimpiarModificarActionPerformed

    private void jbBuscarModificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarModificaActionPerformed

        // TODO add your handling code here:
        int dniM=-1;
        try {
            dniM=Integer.parseInt(JTdniModifcar.getText());
            InquilinoData inqdM = new InquilinoData(conexion);

            Inquilino inquilinoM = inqdM.buscarInquilino(dniM);
            if(inquilinoM != null){
                jTIdModificar.setText(inquilinoM.getIdInquilino()+"");
                JTnombreModificar.setText(inquilinoM.getNombre());
                JTapellidoModificar.setText(inquilinoM.getApellido());
                //String pre = inquilinoM.getCuit()+"";
                //JTcuit_predniModificar.setText(pre.substring(0,2).trim());
                //JTcuit_dniModificar.setText(inquilinoM.getDni()+"");
                //String pos = inquilinoM.getCuit()+"";
                // JTcuit_postdniModificar.setText(pos.substring(pos.length()-2, pos.length()).trim());
                JTcuit_dniModificar.setText(inquilinoM.getCuit()+"");
                JTtelefonoModificar.setText(inquilinoM.getTelefono()+"");
                JTtrabajoModificar.setText(inquilinoM.getTrabajo());
                JTdni_garanteModificar.setText(inquilinoM.getDniGarante()+"");
                JTnombre_garanteModificar.setText(inquilinoM.getNombreGarante());
                JTapellido_garanteModificar.setText(inquilinoM.getApellidoGarante());
                jChBActivoM.setSelected(inquilinoM.isEstado());
                jbActualizar.setEnabled(true);
                jbBorrarModificar.setEnabled(true);

            }else{
                JOptionPane.showMessageDialog(this,"No existe un Cliente con ese DNI");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"DNI Inválido ");
        }
    }//GEN-LAST:event_jbBuscarModificaActionPerformed

    private void jbSalirModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirModificarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jbSalirModificarActionPerformed

    private void jbActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbActualizarActionPerformed
        // TODO add your handling code here:
        long dni =-1,cuit =-1,tel=-1, dniGar=-1;
        int idM=-1;

        dni =Integer.parseInt(JTdniModifcar.getText().trim());
        String nomb = JTnombreModificar.getText().trim();
        String ape = JTapellidoModificar.getText().trim();
        cuit = Long.parseLong(JTcuit_dniModificar.getText());
        tel = Long.parseLong(JTtelefonoModificar.getText().trim());
        String tra = JTtrabajoModificar.getText().trim();
        String apeGar = JTapellido_garanteModificar.getText().trim();
        String nomGar = JTnombre_garanteModificar.getText().trim();
        dniGar = Long.parseLong(JTdni_garanteModificar.getText().trim());
        idM = Integer.parseInt(jTIdModificar.getText().trim());
        boolean activo = jChBActivo.isSelected();
        Inquilino inquilino = new Inquilino(idM, dni, ape, nomb, cuit, tel, tra, apeGar, nomGar, dniGar,activo);

        if(inquilinoData.modificarInquilino(inquilino)){
            JOptionPane.showMessageDialog(this,"Cliente Modificado Exitosamente");
            limpiarCamposModificar();
        }
    }//GEN-LAST:event_jbActualizarActionPerformed

    private void JTdni_garanteModificarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTdni_garanteModificarFocusLost
        // TODO add your handling code here:
        if( JTdni_garanteModificar.getText().length()==0){
            JOptionPane.showMessageDialog(this, "El dni del garante no puede quedar vacio");
            JTdni_garanteModificar.requestFocus();
        }
        else{
            try {
                long prueba = Long.parseLong( JTdni_garanteModificar.getText());

            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Los campos de DNI deben ser numeros");
                JTdni_garanteModificar.requestFocus();
            }
        }
    }//GEN-LAST:event_JTdni_garanteModificarFocusLost

    private void JTtelefonoModificarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTtelefonoModificarFocusLost
        // TODO add your handling code here:
        if(JTtelefonoModificar.getText().length()==0){
            JOptionPane.showMessageDialog(this, "Debe ingresar un telefono de contacto");
            JTtelefonoModificar.requestFocus();
        }
        else{
            try {
               long prueba = Long.parseLong(JTtelefonoModificar.getText());

            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "telefono debe ser un numero");
                JTtelefonoModificar.requestFocus();
            }
        }
    }//GEN-LAST:event_JTtelefonoModificarFocusLost

    private void JTcuit_dniModificarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTcuit_dniModificarFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_JTcuit_dniModificarFocusLost

    private void JTdniModifcarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTdniModifcarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTdniModifcarActionPerformed

    private void JTdniModifcarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTdniModifcarFocusLost
        // TODO add your handling code here:
        if(JTdniModifcar.getText().length()==0){
            JOptionPane.showMessageDialog(this, "DNI no puede quedar vacio");
            JTdniModifcar.requestFocus();
        }
        else{
            try {
                long prueba = Long.parseLong(JTdniModifcar.getText());
                
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "DNI debe ser un numero");
                JTdniModifcar.requestFocus();
            }
        }
    }//GEN-LAST:event_JTdniModifcarFocusLost

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarActionPerformed

        int validacion =0;
        String nombre,apellido,trabajo,nomG, apelG;
        nombre = JTnombre.getText().trim();
        apellido = JTapellido.getText().trim();
        trabajo =JTtrabajo.getText().trim();
        nomG = JTnombre_garante.getText().trim();
        apelG = JTapellido_garante.getText().trim();
        boolean activo = jChBActivo.isSelected();
        if (nombre.equals("")) {
            JTnombre.setBackground(Color.red);
            validacion++;
        }
        if (apellido.equals("")) {
            JTapellido.setBackground(Color.red);
            validacion++;
        }
        if (trabajo.equals("")) {
            JTtrabajo.setBackground(Color.red);
            validacion++;
        }
        if (nomG.equals("")) {
            JTnombre_garante.setBackground(Color.red);
            validacion++;
        }
        if (apelG.equals("")) {
            JTapellido_garante.setBackground(Color.red);
            validacion++;
        }

        if(validacion == 0 ){
            
            Inquilino inqui = new Inquilino();
            inqui.setApellido(apellido);
            inqui.setApellidoGarante(apelG);
            inqui.setCuit(Long.parseLong(JTcuit_dni.getText()));
            inqui.setDni(Long.parseLong(JTdni.getText()));
            inqui.setDniGarante(Long.parseLong(JTdni_garante.getText()));
            inqui.setNombre(nombre);
            inqui.setNombreGarante(nomG);
            inqui.setTelefono(Long.parseLong(JTtelefono.getText()));
            inqui.setTrabajo(trabajo);
            inqui.setEstado(activo);

            InquilinoData iData = new InquilinoData(conexion);
            iData.agregarInquilino(inqui);
            limpiarCamposGuardar();
        }else{
            JOptionPane.showMessageDialog(null, "Debes llenar todos los campos.");
        }
    }//GEN-LAST:event_jBGuardarActionPerformed

    private void JTtelefonoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTtelefonoFocusLost
        if(JTtelefono.getText().length()==0){
            JOptionPane.showMessageDialog(this, "Debe ingresar un telefono de contacto");
            JTtelefono.requestFocus();
        }
        else{
            try {
                long prueba = Long.parseLong(JTtelefono.getText());

            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "telefono debe ser un numero");
                JTtelefono.requestFocus();
            }
        }// TODO add your handling code here:
    }//GEN-LAST:event_JTtelefonoFocusLost

    private void JTdni_garanteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTdni_garanteFocusLost

        if( JTdni_garante.getText().length()==0){
            JOptionPane.showMessageDialog(this, "El dni del garante no puede quedar vacio");
            JTdni_garante.requestFocus();
        }
        else{
            try {
                long prueba = Long.parseLong( JTdni_garante.getText());

            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Los campos de DNI deben ser numeros");
                JTdni_garante.requestFocus();
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_JTdni_garanteFocusLost

    private void JTcuit_dniFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTcuit_dniFocusLost
        if(JTcuit_dni.getText().length()==0){
            JOptionPane.showMessageDialog(this, "Ningun campo del CUIT no puede quedar vacio");
            JTcuit_dni.requestFocus();
        }
        else{
            try {
                long prueba = Long.parseLong(JTcuit_dni.getText());
               
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Los campos de CUIT deben ser numeros");

                JTcuit_dni.requestFocus();
            }
        }  // TODO add your handling code here:
    }//GEN-LAST:event_JTcuit_dniFocusLost

    private void JTdniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTdniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTdniActionPerformed

    private void JTdniFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTdniFocusLost
        if(JTdni.getText().length()==0){
            JOptionPane.showMessageDialog(this, "DNI no puede quedar vacio");
            JTdni.requestFocus();
        }
        else{
            try {
                long prueba = Long.parseLong(JTdni.getText());
               
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "DNI debe ser un numero");
                JTdni.requestFocus();
            }
        }
    }//GEN-LAST:event_JTdniFocusLost

    private void JTdni_garanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTdni_garanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTdni_garanteActionPerformed

    
    

     public void limpiarCamposModificar(){
        JTdniModifcar.setText("");
         JTnombreModificar.setText("");
         JTapellidoModificar.setText("");
         
         JTcuit_dniModificar.setText("");
         
         JTtelefonoModificar.setText(""); 
         JTtrabajoModificar.setText("");
         JTdni_garanteModificar.setText("");
         JTnombre_garanteModificar.setText("");
         JTapellido_garanteModificar.setText("");   
         jTIdModificar.setText("");
         jChBActivoM.setSelected(true);
         jbActualizar.setEnabled(false);
         jbBorrarModificar.setEnabled(false);
     }
     public void limpiarCamposGuardar(){
        JTdni.setText("");
         JTnombre.setText("");
         JTapellido.setText("");
         
         JTcuit_dni.setText("");
           
         JTtelefono.setText(""); 
         JTtrabajo.setText("");
         JTdni_garante.setText("");
         JTnombre_garante.setText("");
         JTapellido_garante.setText("");  
         jChBActivo.setSelected(true);        
     }
     
  
   /* private void llenarCombo(){
  
        for(Inquilino item: listaInquilinos){
         jCBInquilino.addItem(item);
        }
    }*/
    
    
    
     private void armarCabecera() {                
        
        ArrayList<Object> columnas = new ArrayList<Object>();
        columnas.add("codContrato");
        columnas.add("idPropiedad");       
        columnas.add("Caracteristica"); 
        columnas.add("Dirección"); 
        
        for(Object it : columnas) {
        modelo.addColumn(it);        
        }
        jTablaProp.setModel(modelo);
        
    } 
          private void borraFilasTabla(){
   if(modelo!=null){
       int a =modelo.getRowCount()-1;
           for(int i=a;i>=0;i--){   
                modelo.removeRow(i );
           }
    
}
}
          
private void cargaDatos(){
   borraFilasTabla();
   
   Inquilino inq =(Inquilino)jCBInquilino.getSelectedItem();
   
  
   for(ContratoAlquiler p : listaContratos){    
       
       //System.out.println("ver contrato id Inquilno"+p.toString());//chequeo de datos
   if(p.getInquilino().getIdInquilino() == inq.getIdInquilino()){
      
     modelo.addRow(new Object[]{p.getCodContrato(),p.getPropiedad().getIdPropiedad(),p.getPropiedad().getTipo(),p.getPropiedad().getDireccion()});   
   }
   
   }
   } 
private void cargarInquilinos(){
    
    Collections.sort(listaInquilinos, new Comparator<Inquilino>() {
        @Override
        public int compare(Inquilino t, Inquilino t1) {
           return t.getApellido().compareTo(t1.getApellido());
        }
    });
    for(Inquilino item: listaInquilinos){
       jCBInquilino.addItem(item);
    }

}
          

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JTapellido;
    private javax.swing.JTextField JTapellidoModificar;
    private javax.swing.JTextField JTapellido_garante;
    private javax.swing.JTextField JTapellido_garanteModificar;
    private javax.swing.JTextField JTcuit_dni;
    private javax.swing.JTextField JTcuit_dniModificar;
    private javax.swing.JTextField JTdni;
    private javax.swing.JTextField JTdniModifcar;
    private javax.swing.JTextField JTdni_garante;
    private javax.swing.JTextField JTdni_garanteModificar;
    private javax.swing.JTextField JTnombre;
    private javax.swing.JTextField JTnombreModificar;
    private javax.swing.JTextField JTnombre_garante;
    private javax.swing.JTextField JTnombre_garanteModificar;
    private javax.swing.JTextField JTtelefono;
    private javax.swing.JTextField JTtelefonoModificar;
    private javax.swing.JTextField JTtrabajo;
    private javax.swing.JTextField JTtrabajoModificar;
    private javax.swing.JButton jBGuardar;
    private javax.swing.JButton jBImprimir;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<Inquilino> jCBInquilino;
    private javax.swing.JCheckBox jChBActivo;
    private javax.swing.JCheckBox jChBActivoM;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLbApellido4;
    private javax.swing.JLabel jLbApellido5;
    private javax.swing.JLabel jLbApellidoGarante;
    private javax.swing.JLabel jLbApellidoGarante1;
    private javax.swing.JLabel jLbCuit4;
    private javax.swing.JLabel jLbCuit5;
    private javax.swing.JLabel jLbDni4;
    private javax.swing.JLabel jLbDni5;
    private javax.swing.JLabel jLbDniGarante;
    private javax.swing.JLabel jLbDniGarante1;
    private javax.swing.JLabel jLbNombre4;
    private javax.swing.JLabel jLbNombre5;
    private javax.swing.JLabel jLbNombreGarante;
    private javax.swing.JLabel jLbNombreGarante1;
    private javax.swing.JLabel jLbTelefono4;
    private javax.swing.JLabel jLbTelefono5;
    private javax.swing.JLabel jLbTrabajo4;
    private javax.swing.JLabel jLbTrabajo5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTIdModificar;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTablaProp;
    private javax.swing.JButton jbActualizar;
    private javax.swing.JButton jbBorrarModificar;
    private javax.swing.JButton jbBuscarModifica;
    private javax.swing.JButton jbLimpiarModificar;
    private javax.swing.JButton jbSalirListar;
    private javax.swing.JButton jbSalirModificar;
    // End of variables declaration//GEN-END:variables
}
