/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import conexion.Conexion;
import inmo_data.ContratoAlquilerData;
import inmo_data.Propiedad_Inmueble_Data;
import inmo_data.PropietarioData;
import inmo_data.Tipos;
import inmo_data.Tipos.tipos;
import inmo_data.Zonas;
import inmo_data.Zonas.zonas;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import t_final_inmobiliaria_g5.ContratoAlquiler;
import t_final_inmobiliaria_g5.Propiedad_Inmueble;
import t_final_inmobiliaria_g5.Propietario;

/**
 *
 * @author mseba
 */
public class Vista_FormPropiedad extends javax.swing.JInternalFrame {
         Conexion conexion;
         DefaultTableModel modelo;
    /**
     * Creates new form Vista_FormPropiedad
     */
    public Vista_FormPropiedad(Conexion conexion) {
        this.conexion = conexion;
        initComponents();
        llenarComboZona();
        llenarComboTipos();
        cargarPropiedades();
        modelo= new DefaultTableModel();
          
        armarCabeceraTabla();
        
    }

    
      private void llenarComboZona(){
    
       for(zonas zona: zonas.values()){
         
          JMzonas.addItem(zona);
        JMzonas2.addItem(zona);
        ModZona.addItem(zona.toString());
           
        }
    }
     private void llenarComboTipos(){
    
       for(tipos tipo: tipos.values() ){
         
          JMtipo.addItem(tipo);
         JMtipo2.addItem(tipo);
         ModTipo.addItem(tipo.toString());
           
        }
    }
     public void cargarPropiedades(){
        PropietarioData proData =  new PropietarioData(conexion);
        ArrayList<Propiedad_Inmueble> propiedades = new ArrayList<>();
        Propiedad_Inmueble_Data piData = new Propiedad_Inmueble_Data(conexion);
        propiedades = piData.ListarPropiedades(proData);
        for (Propiedad_Inmueble propiedad : propiedades) {
            JCinms.addItem(propiedad);
        }
        }
     
         private void armarCabeceraTabla() {
        ArrayList<Object> cabecera = new ArrayList<>();
        cabecera.add("Codigo");
        cabecera.add("Direccion");
        cabecera.add("Superficie");
        cabecera.add("Precio");
        cabecera.add("Disponibilidad");
        for (Object object : cabecera){ 
         modelo.addColumn(object);
            
        }
        JTabla.setModel(modelo);
    }

           private void borraFilasTabla(){
   if(modelo!=null){
       int a =modelo.getRowCount()-1;

           for(int i=a;i>=0;i--){
   
                modelo.removeRow(i );
           }
            }
         }
        public void limpiarRegistros(){
            JTdir.setText("");
            JTdniProp.setText("");
            JTpMax.setText("");
           
            JTprecio.setText("");
            JTsuoM.setText("");
            JTsup.setText("");
           
            borraFilasTabla();
            
            
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        JMzonas = new javax.swing.JComboBox<>();
        JMtipo = new javax.swing.JComboBox<>();
        JTdniProp = new javax.swing.JTextField();
        JTdir = new javax.swing.JTextField();
        JTsup = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        JTprecio = new javax.swing.JTextField();
        jButton12 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        JMzonas2 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        JMtipo2 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        JTsuoM = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        JTpMax = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTabla = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        codBorrar = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        ModCod = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        ModZona = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        ModTipo = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        ModDir = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        ModSup = new javax.swing.JTextField();
        ModPrecio = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        JCinms = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setText("DNI Propietario");

        jLabel2.setText("Zona");

        jLabel3.setText("Tipo");

        jLabel4.setText("Direccion");

        jLabel5.setText("Superficie");

        JMzonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMzonasActionPerformed(evt);
            }
        });

        JMtipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMtipoActionPerformed(evt);
            }
        });

        JTdniProp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                JTdniPropFocusLost(evt);
            }
        });

        JTsup.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                JTsupFocusLost(evt);
            }
        });

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel6.setText("Precio");

        JTprecio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                JTprecioFocusLost(evt);
            }
        });

        jButton12.setText("Limpiar");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JTdniProp, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JTdir)
                                    .addComponent(JTsup)
                                    .addComponent(JTprecio, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(JMtipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(JMzonas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(241, 241, 241))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(65, 65, 65)))
                        .addGap(14, 14, 14)
                        .addComponent(jButton12)
                        .addGap(51, 51, 51)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTdniProp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JMzonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JMtipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTdir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(JTsup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTprecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton12)
                    .addComponent(jButton2))
                .addGap(168, 168, 168))
        );

        jTabbedPane1.addTab("Cargar Inmueble", jPanel1);

        jLabel7.setText("Zona");

        JMzonas2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMzonas2ActionPerformed(evt);
            }
        });

        jLabel8.setText("Tipo");

        jLabel9.setText("Superficie Min");

        jLabel10.setText("Precio MAx");

        JTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        JTabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTabla);

        jButton3.setText("Consultar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Salir");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton11.setText("Alquilar");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton13.setText("Limpiar");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel7))
                        .addGap(64, 64, 64)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JMzonas2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JMtipo2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JTsuoM, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(JTpMax, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(77, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jButton11)
                .addGap(35, 35, 35)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton13)
                .addGap(30, 30, 30)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(JMzonas2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JMtipo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(JTsuoM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(JTpMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton11)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton13))
                .addContainerGap(123, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Inm por Caract.", jPanel2);

        jLabel17.setText("Ingrese el codigo del inmueble");

        jButton8.setText("Borrar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("Salir");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("Activar");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(jLabel17))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(codBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(221, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addComponent(codBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jButton8)
                .addGap(32, 32, 32)
                .addComponent(jButton10)
                .addGap(34, 34, 34)
                .addComponent(jButton9)
                .addContainerGap(332, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Borrar/activar  Inm", jPanel4);

        jLabel11.setText("Codigo Inmueble");

        ModCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModCodActionPerformed(evt);
            }
        });

        jButton5.setText("Buscar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel12.setText("zona");

        jLabel13.setText("Tipo");

        jLabel14.setText("direccion");

        jLabel15.setText("Superficie");

        jLabel16.setText("Precio");

        jButton6.setText("Actualizar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Salir");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        JCinms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCinmsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(247, 247, 247)
                                .addComponent(jLabel16))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(171, 171, 171)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ModPrecio)
                                    .addComponent(ModSup)
                                    .addComponent(ModDir)
                                    .addComponent(ModTipo, 0, 195, Short.MAX_VALUE)
                                    .addComponent(ModZona, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(239, 239, 239)
                                .addComponent(jLabel15))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(257, 257, 257)
                                .addComponent(jLabel13))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(134, 134, 134)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(87, 87, 87)
                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(243, 243, 243)
                                .addComponent(jLabel14))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(255, 255, 255)
                                .addComponent(jLabel12)))
                        .addGap(0, 210, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel11)
                .addGap(55, 55, 55)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JCinms, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ModCod, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addGap(67, 67, 67))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(143, Short.MAX_VALUE)
                .addComponent(JCinms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ModCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11))
                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ModZona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ModTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ModDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ModSup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ModPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton7))
                .addGap(20, 20, 20))
        );

        jTabbedPane1.addTab("Modificar Inm", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JMtipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMtipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JMtipoActionPerformed

    private void JTdniPropFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTdniPropFocusLost
              try {
              Integer.parseInt(JTdniProp.getText());
        } catch (NumberFormatException ex) {
                  JOptionPane.showMessageDialog(this, "Dni debe ser un numero");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_JTdniPropFocusLost

    private void JTsupFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTsupFocusLost
                try {
              Double.parseDouble(JTsup.getText());
        } catch (NumberFormatException ex) {
                  JOptionPane.showMessageDialog(this, "Superficie debe ser un numero");
        }// TODO add your handling code here:
    }//GEN-LAST:event_JTsupFocusLost

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            int camposCompletos=4;
            if(JTdniProp.getText().length()==0){
                camposCompletos--;
                JTdniProp.setBackground(Color.red);
            }
            if(JTsup.getText().length()==0){
                JTsup.setBackground(Color.red);
                camposCompletos--;
            }
            if(JTdir.getText().length()==0){
                JTdir.setBackground(Color.red);
                camposCompletos--;
            }
            if(JTprecio.getText().length()==0){
                JTprecio.setBackground(Color.red);
                camposCompletos--;
            }
            if(camposCompletos<4){
                JOptionPane.showMessageDialog(this, "Debe completar todos los campos");
            }
            else{
            Propiedad_Inmueble prop = new Propiedad_Inmueble();
            Propiedad_Inmueble_Data propieData = new Propiedad_Inmueble_Data(conexion);
            PropietarioData proData = new PropietarioData(conexion);
            prop.setDireccion(JTdir.getText());
            prop.setSuperficie(Double.parseDouble(JTsup.getText()));
            prop.setTipo(JMtipo.getSelectedItem().toString());
            prop.setZona(JMzonas.getSelectedItem().toString());
            prop.setPrecio(Double.parseDouble(JTprecio.getText()));
            prop.setPropietario(proData.buscarPropietario(Long.parseLong(JTdniProp.getText())));
            propieData.cargarInmueble(prop,Integer.parseInt(JTdniProp.getText()));
            JTdniProp.setBackground(Color.white);
            JTsup.setBackground(Color.white);
            JTdir.setBackground(Color.white);
             JTprecio.setBackground(Color.white);
             limpiarRegistros();
            }
            

// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void JMzonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMzonasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JMzonasActionPerformed

    private void JMzonas2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMzonas2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JMzonas2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       int correctos =2;
       borraFilasTabla()      ;
        Propiedad_Inmueble_Data PimData = new Propiedad_Inmueble_Data(conexion);
       ContratoAlquilerData contData = new ContratoAlquilerData(conexion);
        LocalDate testigo =  LocalDate.now();
        String zona = JMzonas2.getSelectedItem().toString();
        String tipo = JMtipo2.getSelectedItem().toString();
        String supM =JTsuoM.getText();
        String pMax = JTpMax.getText();
        
        if(supM.length()==0){
            supM= "1";
        }
        if(pMax.length()==0){
            pMax="9999999999";
        }
        try {
            Double.parseDouble(supM);
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Superficie debe ser un numero");
            JTsuoM.setBackground(Color.red);
            correctos--;
        }
            try {
            Double.parseDouble(pMax);
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Precio maximo debe ser un numero");
            JTpMax.setBackground(Color.red);
            correctos--;
        }
            if(correctos==2){
                JTsuoM.setBackground(Color.white);
                JTpMax.setBackground(Color.white);
       ArrayList<Propiedad_Inmueble> propiedades = PimData.buscarInmPorCaract(tipo, zona, supM, pMax);
      
        for (Propiedad_Inmueble propiedad : propiedades) {
             String disponible = "DISPONIBLE";
            String cod = propiedad.getCodigo();
            String dir = propiedad.getDireccion();
            String sup= ""+ propiedad.getSuperficie();
            String precio = ""+propiedad.getPrecio();
            
         
            ArrayList<ContratoAlquiler> contratosProp = contData.buscarContratosPorInmueble(propiedad);
            if(contratosProp.size()>=0){
                for (ContratoAlquiler contrato : contratosProp) {
                    
                    if(contrato.getFecha_Final().isAfter(testigo) || contrato.getFecha_Final().isEqual(testigo)){
                        disponible = contrato.getFecha_Final().plusDays(1).toString();
                        testigo = contrato.getFecha_Final();
                    }
                   
                }
                 modelo.addRow(new Object[]{cod, propiedad.getDireccion(), propiedad.getSuperficie() , propiedad.getPrecio(), disponible});
            }
        }
            }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
            Propiedad_Inmueble_Data InmData= new Propiedad_Inmueble_Data(conexion);
            PropietarioData propie = new PropietarioData(conexion);
            Propiedad_Inmueble prop = InmData.buscarInmPorCodigo(ModCod.getText(), propie);
            JCinms.setSelectedItem(prop);
           
            
            
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        Propiedad_Inmueble_Data InmData= new Propiedad_Inmueble_Data(conexion); 
      Propiedad_Inmueble prop = InmData.buscarInmPorCodigo(ModCod.getText().toUpperCase());
      int id = prop.getIdPropiedad();
      String zona = ModZona.getSelectedItem().toString();
      String tipo = ModTipo.getSelectedItem().toString();
      String pMax = ModPrecio.getText();
      String supmin = ModSup.getText();
      String direcc = ModDir.getText();
      String nuCod = tipo.substring(0,2)+id;
      InmData.ModificarInmueble(id, nuCod, tipo, zona, pMax, supmin, direcc);
      limpiarRegistros();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void ModCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModCodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModCodActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        Propiedad_Inmueble_Data pData = new Propiedad_Inmueble_Data(conexion);
        pData.borrarImueble(codBorrar.getText()); 
        JOptionPane.showMessageDialog(this, "El inmueble ya no esta activo en el sistema");// TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
     dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
             Propiedad_Inmueble_Data pData = new Propiedad_Inmueble_Data(conexion);
        pData.reactivarrImueble(codBorrar.getText()); 
        JOptionPane.showMessageDialog(this, "El inmueble se ha activado");        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void JCinmsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCinmsActionPerformed
           Propiedad_Inmueble prop = (Propiedad_Inmueble) JCinms.getSelectedItem();
           ModDir.setText(prop.getDireccion());
            ModPrecio.setText(""+prop.getPrecio());
            ModSup.setText(""+ prop.getSuperficie());
            ModTipo.setSelectedItem(prop.getTipo());
            ModZona.setSelectedItem(prop.getZona());        // TODO add your handling code here:
    }//GEN-LAST:event_JCinmsActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed
   String alquilarDesdeTabla="";
    private void JTablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTablaMouseClicked
        
        alquilarDesdeTabla = (String)JTabla.getValueAt(JTabla.getSelectedRow(), 0);
    }//GEN-LAST:event_JTablaMouseClicked

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        if(!alquilarDesdeTabla.equals("")){
        Vista_Contrato cont = new Vista_Contrato(conexion);
         cont.setVisible(true);
        this.getDesktopPane().add(cont);
        this.getDesktopPane().repaint();
        this.getDesktopPane().moveToFront(cont); 
        cont.getJTcodBusc().setText(alquilarDesdeTabla);
        Propiedad_Inmueble_Data proData = new Propiedad_Inmueble_Data(conexion);
                PropietarioData propie = new PropietarioData(conexion);
                Propiedad_Inmueble propi = proData.buscarInmPorCodigo(alquilarDesdeTabla,propie);
               cont.getJCpropiedades().setSelectedItem(propi);
        
// TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed
         else {JOptionPane.showMessageDialog(this, "Debe elegir un inmueble");}
    }
    
    private void JTprecioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTprecioFocusLost
        try {
            Double.parseDouble(JTprecio.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Debe ingresar un numero para precio");
        }
 // TODO add your handling code here:
    }//GEN-LAST:event_JTprecioFocusLost

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        limpiarRegistros();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        limpiarRegistros();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed
     
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Propiedad_Inmueble> JCinms;
    private javax.swing.JComboBox<tipos> JMtipo;
    private javax.swing.JComboBox<tipos> JMtipo2;
    private javax.swing.JComboBox<zonas> JMzonas;
    private javax.swing.JComboBox<zonas> JMzonas2;
    private javax.swing.JTable JTabla;
    private javax.swing.JTextField JTdir;
    private javax.swing.JTextField JTdniProp;
    private javax.swing.JTextField JTpMax;
    private javax.swing.JTextField JTprecio;
    private javax.swing.JTextField JTsuoM;
    private javax.swing.JTextField JTsup;
    private javax.swing.JTextField ModCod;
    private javax.swing.JTextField ModDir;
    private javax.swing.JTextField ModPrecio;
    private javax.swing.JTextField ModSup;
    private javax.swing.JComboBox<String> ModTipo;
    private javax.swing.JComboBox<String> ModZona;
    private javax.swing.JTextField codBorrar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables



}