/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;
import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;
import conexion.Conexion;
import inmo_data.ContratoAlquilerData;
import inmo_data.InquilinoData;
import inmo_data.Propiedad_Inmueble_Data;
import inmo_data.PropietarioData;
import java.text.SimpleDateFormat;
import java.time.Instant;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import t_final_inmobiliaria_g5.ContratoAlquiler;
import t_final_inmobiliaria_g5.Inquilino;
import t_final_inmobiliaria_g5.Propiedad_Inmueble;
import t_final_inmobiliaria_g5.Propietario;

/**
 *
 * @author mseba
 */
public class Vista_Contrato extends javax.swing.JInternalFrame {
        Conexion conexion;
        DefaultTableModel modelo;
    /**
     * Creates new form Vusta_Contrato
     */
    public Vista_Contrato(Conexion conexion) {
        this.conexion = conexion;
        initComponents();
        
        cargarPropiedades();
        cargarInquilinos();
        cargarPropietarios();
         modelo= new DefaultTableModel();
        armarCabeceraTabla();
    }
    
     private void armarCabeceraTabla() {
        ArrayList<Object> cabecera = new ArrayList<>();
        cabecera.add("Codigo");
        cabecera.add("vendedor");
        cabecera.add("Cod propiedad");
        cabecera.add("DNI Inquilino");
        cabecera.add("Fecha Inicio");
        cabecera.add("Fecha Final");
        for (Object object : cabecera){ 
         modelo.addColumn(object);
            
        }
        JTabla.setModel(modelo);
    }

    public void cargarPropiedades(){
        PropietarioData proData =  new PropietarioData(conexion);
        ArrayList<Propiedad_Inmueble> propiedades = new ArrayList<>();
        Propiedad_Inmueble_Data piData = new Propiedad_Inmueble_Data(conexion);
        propiedades = piData.buscarInmDisponibles(proData);
        for (Propiedad_Inmueble propiedad : propiedades) {
            JCpropiedades.addItem(propiedad);
            JCpropiedades2.addItem(propiedad);
        }
        }
    
        public void cargarInquilinos(){
            InquilinoData inquiData = new InquilinoData(conexion);
            ArrayList<Inquilino> inquis = new ArrayList<>();
            inquis =(ArrayList<Inquilino>) inquiData.listaTodosInquilinos();
            for (Inquilino inqui : inquis) {
                JCinquilinos.addItem(inqui);
                JCinqui2.addItem(inqui);
                
            }
        }
        public void cargarPropietarios(){
            PropietarioData proData = new PropietarioData(conexion);
            ArrayList<Propietario> props = new ArrayList<>();
            props = (ArrayList)proData.listaTodosPropietarios();
            for (Propietario prop : props) {
                JCpropietarios.addItem(prop);
            }
        }
        
         private void borraFilasTabla(){
   if(modelo!=null){
       int a =modelo.getRowCount()-1;

           for(int i=a;i>=0;i--){
   
                modelo.removeRow(i );
           }
            }
         }
        public void limpiarRegistros(){
            JTvendedor.setText("");
            JTcodBusc.setText("");
            JCbusInqu.setText("");
            JDinicio.setDate(null);
            JDfinal.setDate(null);
            JTcodRes.setText("");
            JTcodB.setText("");
            JCfin.setDate(null);
            borraFilasTabla();
            JRBvencidos.setSelected(false);
            JRBvigente.setSelected(false);
            
        }
        
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        JTvendedor = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JCpropiedades = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        JTcodBusc = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        JCinquilinos = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        JCbusInqu = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        JDinicio = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        JDfinal = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        JTcodRes = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        JTcodB = new javax.swing.JTextField();
        JCfin = new com.toedter.calendar.JDateChooser();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        JCinqui2 = new javax.swing.JComboBox<>();
        JBbusXinq = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        JCpropiedades2 = new javax.swing.JComboBox<>();
        JBconXpropiedad = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        JCpropietarios = new javax.swing.JComboBox<>();
        JBbusXpropietario = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTabla = new javax.swing.JTable();
        JRBvigente = new javax.swing.JRadioButton();
        JRBvencidos = new javax.swing.JRadioButton();
        jButton9 = new javax.swing.JButton();
        JBlimpiar2 = new javax.swing.JButton();

        jLabel1.setText("Vendedor");

        jLabel2.setText("Inmueble");

        jLabel3.setText("Cod :");

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Inquilino");

        jLabel6.setText("DNI:");

        jButton2.setText("Buscar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel7.setText("Inicio del Contrato");

        jLabel8.setText("Fin del Contrato");

        jButton3.setText("Cargar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Salir");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton10.setText("Limpiar");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(JDinicio, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addComponent(JDfinal, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(JTvendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(JCpropiedades, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JCinquilinos, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(43, 43, 43)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(95, 95, 95)
                                .addComponent(jLabel7)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(JCbusInqu, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                                    .addComponent(JTcodBusc))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButton1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel4))
                                    .addComponent(jButton2)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton10)
                .addGap(80, 80, 80)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(145, 145, 145))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JTvendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JTcodBusc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(JCpropiedades)
                        .addComponent(jButton1))
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(40, 40, 40)
                .addComponent(jLabel5)
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JCinquilinos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(JCbusInqu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JDinicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JDfinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 161, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton3)
                    .addComponent(jButton10))
                .addGap(54, 54, 54))
        );

        jTabbedPane1.addTab("Subir Contrato", jPanel1);

        jLabel9.setText("Codigo de Contrato");

        jButton5.setText("Rescindir");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton8.setText("Salir");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addComponent(jLabel9))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(JTcodRes, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(270, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel9)
                .addGap(14, 14, 14)
                .addComponent(JTcodRes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jButton5)
                .addGap(46, 46, 46)
                .addComponent(jButton8)
                .addContainerGap(340, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Rescindir Contrato", jPanel2);

        jLabel10.setText("Codigo Contrato");

        jButton6.setText("Renovar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Salir");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addComponent(jLabel10))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(JTcodB, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton6)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jButton7))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(JCfin, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(235, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(JTcodB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(JCfin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(jButton6)
                .addGap(39, 39, 39)
                .addComponent(jButton7)
                .addContainerGap(235, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Renovar Contrato", jPanel3);

        jLabel11.setText("Buscar Contratos de Inquilino");

        JCinqui2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        JCinqui2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCinqui2ActionPerformed(evt);
            }
        });

        JBbusXinq.setText("buscar");
        JBbusXinq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBbusXinqActionPerformed(evt);
            }
        });

        jLabel13.setText("Buscar Contratos de Propiedad");

        JBconXpropiedad.setText("buscar");
        JBconXpropiedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBconXpropiedadActionPerformed(evt);
            }
        });

        jLabel15.setText("Buscar Contratos de propietario");

        JBbusXpropietario.setText("Buscar");
        JBbusXpropietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBbusXpropietarioActionPerformed(evt);
            }
        });

        JTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(JTabla);

        JRBvigente.setText("Vigentes");
        JRBvigente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRBvigenteActionPerformed(evt);
            }
        });

        JRBvencidos.setText("Vencidos");
        JRBvencidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRBvencidosActionPerformed(evt);
            }
        });

        jButton9.setText("Salir");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        JBlimpiar2.setText("Limpiar");
        JBlimpiar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBlimpiar2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JCinqui2, 0, 319, Short.MAX_VALUE)
                    .addComponent(JCpropiedades2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JCpropietarios, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JBbusXinq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JBconXpropiedad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JBbusXpropietario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(JRBvigente)
                        .addGap(63, 63, 63)
                        .addComponent(JRBvencidos))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JBlimpiar2, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE))))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(JCinqui2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBbusXinq))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(JCpropiedades2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBconXpropiedad))
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JCpropietarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(JBbusXpropietario))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JRBvigente)
                    .addComponent(JRBvencidos))
                .addGap(26, 26, 26)
                .addComponent(JBlimpiar2)
                .addGap(48, 48, 48)
                .addComponent(jButton9)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Buscar Contrato", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 612, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                Propiedad_Inmueble_Data proData = new Propiedad_Inmueble_Data(conexion);
                PropietarioData propie = new PropietarioData(conexion);
                Propiedad_Inmueble propi = proData.buscarInmPorCodigo(JTcodBusc.getText(),propie);
                JCpropiedades.setSelectedItem(propi);
                
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            InquilinoData inquiData = new InquilinoData(conexion);
            Inquilino inqui = inquiData.buscarInquilino(Long.parseLong(JCbusInqu.getText()));
            JCinquilinos.setSelectedItem(inqui);
            

// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Date inicio = JDinicio.getDate();
ZoneId defaultZoneId = ZoneId.systemDefault();
Instant instant = inicio.toInstant();
LocalDate localInicio = instant
    .atZone(defaultZoneId).toLocalDate();

    Date fin = JDfinal.getDate();
ZoneId defaultZoneId2 = ZoneId.systemDefault();
Instant instant2 = fin.toInstant();
LocalDate localFinal = instant2
    .atZone(defaultZoneId).toLocalDate();
        ContratoAlquilerData coAlData = new ContratoAlquilerData(conexion);
        ArrayList<ContratoAlquiler> contratosDelInmueble = coAlData.buscarContratosPorInmueble((Propiedad_Inmueble)JCpropiedades.getSelectedItem());
        boolean disponible = true;
        for (ContratoAlquiler contratoAlquiler : contratosDelInmueble) {
            if(localInicio.isBefore(contratoAlquiler.getFecha_Final().plusDays(1))){
            disponible = false;
            }
            
        }
        if(disponible){
        ContratoAlquiler nuevoContrato = new ContratoAlquiler(JTvendedor.getText(),(Propiedad_Inmueble) JCpropiedades.getSelectedItem(), (Inquilino) JCinquilinos.getSelectedItem(), localInicio, localFinal);   
        
         System.out.println(nuevoContrato.getFecha_Inicio());
         System.out.println(nuevoContrato.getFecha_Final());
         coAlData.firmarContrato(nuevoContrato);
         limpiarRegistros();
        }
        else{
            JOptionPane.showMessageDialog(this, "Es imposible alquilar en las fechas elegidas");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
            ContratoAlquilerData caData = new ContratoAlquilerData(conexion);
             ContratoAlquiler cont =  caData.buscarContrato(JTcodRes.getText());
             caData.rescindirContrato(cont);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
         ContratoAlquilerData caData = new ContratoAlquilerData(conexion);
         ContratoAlquiler cont =  caData.buscarContrato(JTcodB.getText());
          Date nuFinal = JCfin.getDate();
          ZoneId defaultZoneId = ZoneId.systemDefault();
          Instant instant = nuFinal.toInstant();
          LocalDate localFinal = instant
                        .atZone(defaultZoneId).toLocalDate();
         caData.renovarContrato(cont, localFinal);
         limpiarRegistros();
         
// TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void JRBvencidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRBvencidosActionPerformed
         borraFilasTabla();
        if((JRBvencidos.isSelected()&& JRBvigente.isSelected()) || (!JRBvencidos.isSelected()&& !JRBvigente.isSelected())){
          for (ContratoAlquiler contrato : contratos) {
             modelo.addRow(new Object[]{contrato.getCodContrato(), contrato.getVendedor(), contrato.getPropiedad().getCodigo() , contrato.getInquilino().getDni(), contrato.getFecha_Inicio(), contrato.getFecha_Final()});
         }
         }
         else if(JRBvencidos.isSelected()&& !JRBvigente.isSelected()){
             ArrayList<ContratoAlquiler> arrayAuxiliar = new ArrayList<>();
             for (ContratoAlquiler contrato : contratos) {
                 if(contrato.getFecha_Final().isBefore(LocalDate.now()))
                     arrayAuxiliar.add(contrato);
             }
              for (ContratoAlquiler contrato : arrayAuxiliar) {
             modelo.addRow(new Object[]{contrato.getCodContrato(), contrato.getVendedor(), contrato.getPropiedad().getCodigo() , contrato.getInquilino().getDni(), contrato.getFecha_Inicio(), contrato.getFecha_Final()});
         }
         }
         else if(!JRBvencidos.isSelected()&& JRBvigente.isSelected()){
             ArrayList<ContratoAlquiler> arrayAuxiliar = new ArrayList<>();
             for (ContratoAlquiler contrato : contratos) {
                 if((contrato.getFecha_Final().isAfter(LocalDate.now())|| contrato.getFecha_Final().isEqual(LocalDate.now()))){
                     arrayAuxiliar.add(contrato);
             }
             }
              for (ContratoAlquiler contrato : arrayAuxiliar) {
             modelo.addRow(new Object[]{contrato.getCodContrato(), contrato.getVendedor(), contrato.getPropiedad().getCodigo() , contrato.getInquilino().getDni(), contrato.getFecha_Inicio(), contrato.getFecha_Final()});
         }
         }        // TODO add your handling code here:
    }//GEN-LAST:event_JRBvencidosActionPerformed

    private void JCinqui2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCinqui2ActionPerformed
       
        
              // TODO add your handling code here:
    }//GEN-LAST:event_JCinqui2ActionPerformed

    ArrayList<ContratoAlquiler> contratos;
    
    private void JBbusXinqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBbusXinqActionPerformed
       borraFilasTabla();
        limpiarRegistros();
        ContratoAlquilerData contData = new ContratoAlquilerData(conexion);
      contratos = contData.mostrarContratosPorInquilino((Inquilino)JCinqui2.getSelectedItem());  
        for (ContratoAlquiler contrato : contratos) {
             modelo.addRow(new Object[]{contrato.getCodContrato(), contrato.getVendedor(), contrato.getPropiedad().getCodigo() , contrato.getInquilino().getDni(), contrato.getFecha_Inicio(), contrato.getFecha_Final()});
            
        }
           JRBvencidos.setSelected(true);
           JRBvigente.setSelected(true);
// TODO add your handling code here:
    }//GEN-LAST:event_JBbusXinqActionPerformed

    private void JBconXpropiedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBconXpropiedadActionPerformed
        borraFilasTabla();
        ContratoAlquilerData contData = new ContratoAlquilerData(conexion);
        contratos = contData.buscarContratosPorInmueble((Propiedad_Inmueble)JCpropiedades2.getSelectedItem());  
        for (ContratoAlquiler contrato : contratos) {
             modelo.addRow(new Object[]{contrato.getCodContrato(), contrato.getVendedor(), contrato.getPropiedad().getCodigo() , contrato.getInquilino().getDni(), contrato.getFecha_Inicio(), contrato.getFecha_Final()});
        // TODO add your handling code here:
    }//GEN-LAST:event_JBconXpropiedadActionPerformed
      JRBvencidos.setSelected(true);
           JRBvigente.setSelected(true);
    }
    private void JBbusXpropietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBbusXpropietarioActionPerformed
        borraFilasTabla();
        ContratoAlquilerData contData = new ContratoAlquilerData(conexion);
         contratos = contData.mostrarContratosPorPropietario((Propietario)JCpropietarios.getSelectedItem());  
        for (ContratoAlquiler contrato : contratos) {
             modelo.addRow(new Object[]{contrato.getCodContrato(), contrato.getVendedor(), contrato.getPropiedad().getCodigo() , contrato.getInquilino().getDni(), contrato.getFecha_Inicio(), contrato.getFecha_Final()});       // TODO add your handling code here:
    }//GEN-LAST:event_JBbusXpropietarioActionPerformed
       JRBvencidos.setSelected(true);
           JRBvigente.setSelected(true);
    }
    
    
    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
      dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        limpiarRegistros();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void JBlimpiar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBlimpiar2ActionPerformed
         limpiarRegistros();        // TODO add your handling code here:
    }//GEN-LAST:event_JBlimpiar2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
    dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void JRBvigenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRBvigenteActionPerformed
         borraFilasTabla();
        if((JRBvencidos.isSelected()&& JRBvigente.isSelected()) || (!JRBvencidos.isSelected()&& !JRBvigente.isSelected())){
          for (ContratoAlquiler contrato : contratos) {
             modelo.addRow(new Object[]{contrato.getCodContrato(), contrato.getVendedor(), contrato.getPropiedad().getCodigo() , contrato.getInquilino().getDni(), contrato.getFecha_Inicio(), contrato.getFecha_Final()});
         }
         }
         else if(JRBvencidos.isSelected()&& !JRBvigente.isSelected()){
             ArrayList<ContratoAlquiler> arrayAuxiliar = new ArrayList<>();
             for (ContratoAlquiler contrato : contratos) {
                 if(contrato.getFecha_Final().isBefore(LocalDate.now()))
                     arrayAuxiliar.add(contrato);
             }
              for (ContratoAlquiler contrato : arrayAuxiliar) {
             modelo.addRow(new Object[]{contrato.getCodContrato(), contrato.getVendedor(), contrato.getPropiedad().getCodigo() , contrato.getInquilino().getDni(), contrato.getFecha_Inicio(), contrato.getFecha_Final()});
         }
         }
         else if(!JRBvencidos.isSelected()&& JRBvigente.isSelected()){
             ArrayList<ContratoAlquiler> arrayAuxiliar = new ArrayList<>();
             for (ContratoAlquiler contrato : contratos) {
                 if((contrato.getFecha_Final().isAfter(LocalDate.now())|| contrato.getFecha_Final().isEqual(LocalDate.now()))){
                     arrayAuxiliar.add(contrato);
             }
             }
              for (ContratoAlquiler contrato : arrayAuxiliar) {
             modelo.addRow(new Object[]{contrato.getCodContrato(), contrato.getVendedor(), contrato.getPropiedad().getCodigo() , contrato.getInquilino().getDni(), contrato.getFecha_Inicio(), contrato.getFecha_Final()});
         }
         }
             // TODO add your handling code here:
    }//GEN-LAST:event_JRBvigenteActionPerformed

    public void setJTcodBusc(JTextField JTcodBusc) {
        this.JTcodBusc = JTcodBusc;
    }

    public JTextField getJTcodBusc() {
        return JTcodBusc;
    }

    public JComboBox<Propiedad_Inmueble> getJCpropiedades() {
        return JCpropiedades;
    }

    public void setJCpropiedades(JComboBox<Propiedad_Inmueble> JCpropiedades) {
        this.JCpropiedades = JCpropiedades;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBbusXinq;
    private javax.swing.JButton JBbusXpropietario;
    private javax.swing.JButton JBconXpropiedad;
    private javax.swing.JButton JBlimpiar2;
    private javax.swing.JTextField JCbusInqu;
    private com.toedter.calendar.JDateChooser JCfin;
    private javax.swing.JComboBox<Inquilino> JCinqui2;
    private javax.swing.JComboBox<Inquilino> JCinquilinos;
    private javax.swing.JComboBox<Propiedad_Inmueble> JCpropiedades;
    private javax.swing.JComboBox<Propiedad_Inmueble> JCpropiedades2;
    private javax.swing.JComboBox<Propietario> JCpropietarios;
    private com.toedter.calendar.JDateChooser JDfinal;
    private com.toedter.calendar.JDateChooser JDinicio;
    private javax.swing.JRadioButton JRBvencidos;
    private javax.swing.JRadioButton JRBvigente;
    private javax.swing.JTable JTabla;
    private javax.swing.JTextField JTcodB;
    private javax.swing.JTextField JTcodBusc;
    private javax.swing.JTextField JTcodRes;
    private javax.swing.JTextField JTvendedor;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
