/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Document;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;
import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;
import conexion.Conexion;
import inmo_data.ContratoAlquilerData;
import inmo_data.InquilinoData;
import inmo_data.Propiedad_Inmueble_Data;
import inmo_data.PropietarioData;
import java.awt.Color;
import java.awt.Font;
import java.io.FileOutputStream;
import java.text.SimpleDateFormat;
import java.time.Instant;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import t_final_inmobiliaria_g5.ContratoAlquiler;
import t_final_inmobiliaria_g5.Inquilino;
import t_final_inmobiliaria_g5.Propiedad_Inmueble;
import t_final_inmobiliaria_g5.Propietario;

/**
 *
 * @author mseba
 */
public class Vista_Contrato extends javax.swing.JInternalFrame {
        Conexion conexion;
        DefaultTableModel modelo;
    /**
     * Creates new form Vusta_Contrato
     */
    public Vista_Contrato(Conexion conexion) {
        this.conexion = conexion;
        initComponents();
        
        cargarPropiedades();
        cargarInquilinos();
        cargarPropietarios();
         modelo= new DefaultTableModel();
        armarCabeceraTabla();
    }
    
     private void armarCabeceraTabla() {
        ArrayList<Object> cabecera = new ArrayList<>();
        cabecera.add("Codigo");
        cabecera.add("vendedor");
        cabecera.add("Cod propiedad");
        cabecera.add("DNI Inquilino");
        cabecera.add("Fecha Inicio");
        cabecera.add("Fecha Final");
        for (Object object : cabecera){ 
         modelo.addColumn(object);
            
        }
        JTcontratos.setModel(modelo);
    }

    public void cargarPropiedades(){
        PropietarioData proData =  new PropietarioData(conexion);
        ArrayList<Propiedad_Inmueble> propiedades = new ArrayList<>();
        Propiedad_Inmueble_Data piData = new Propiedad_Inmueble_Data(conexion);
        propiedades = piData.buscarInmDisponibles(proData);
        for (Propiedad_Inmueble propiedad : propiedades) {
            JCpropiedades.addItem(propiedad);
            JCpropiedades2.addItem(propiedad);
        }
        }
    
        public void cargarInquilinos(){
            InquilinoData inquiData = new InquilinoData(conexion);
            ArrayList<Inquilino> inquis = new ArrayList<>();
            inquis =(ArrayList<Inquilino>) inquiData.listaTodosInquilinos();
            for (Inquilino inqui : inquis) {
                JCinquilinos.addItem(inqui);
                JCinqui2.addItem(inqui);
                
            }
        }
        public void cargarPropietarios(){
            PropietarioData proData = new PropietarioData(conexion);
            ArrayList<Propietario> props = new ArrayList<>();
            props = (ArrayList)proData.listaTodosPropietarios();
            for (Propietario prop : props) {
                JCpropietarios.addItem(prop);
            }
        }
        
         private void borraFilasTabla(){
   if(modelo!=null){
       int a =modelo.getRowCount()-1;

           for(int i=a;i>=0;i--){
   
                modelo.removeRow(i );
           }
            }
         }
        public void limpiarRegistros(){
            JTvendedor.setText("");
            JTcodBusc.setText("");
            JCbusInqu.setText("");
            JDinicio.setDate(null);
            JDfinal.setDate(null);
            JTcodRes.setText("");
            JTcodB.setText("");
            JCfin.setDate(null);
            borraFilasTabla();
            JRBvencidos.setSelected(false);
            JRBvigente.setSelected(false);
            
        }
        
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        JTvendedor = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JCpropiedades = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        JTcodBusc = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        JCinquilinos = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        JCbusInqu = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        JDinicio = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        JDfinal = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        JTcodRes = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        JTcodB = new javax.swing.JTextField();
        JCfin = new com.toedter.calendar.JDateChooser();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        JCinqui2 = new javax.swing.JComboBox<>();
        JBbusXinq = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        JCpropiedades2 = new javax.swing.JComboBox<>();
        JBconXpropiedad = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        JCpropietarios = new javax.swing.JComboBox<>();
        JBbusXpropietario = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTcontratos = new javax.swing.JTable();
        JRBvigente = new javax.swing.JRadioButton();
        JRBvencidos = new javax.swing.JRadioButton();
        jButton9 = new javax.swing.JButton();
        JBlimpiar2 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        JDchoinegral = new com.toedter.calendar.JDateChooser();
        jBImprimir = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setText("Vendedor");

        jLabel2.setText("Inmueble");

        jLabel3.setText("Cod :");

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Inquilino");

        jLabel6.setText("DNI:");

        jButton2.setText("Buscar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel7.setText("Inicio del Contrato");

        jLabel8.setText("Fin del Contrato");

        jButton3.setText("Cargar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Salir");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton10.setText("Limpiar");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(JCpropiedades, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(JCinquilinos, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(43, 43, 43)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel6)))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGap(86, 86, 86)
                                    .addComponent(jLabel7))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(60, 60, 60)
                                    .addComponent(jButton3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addComponent(jButton10))))
                            .addComponent(JDinicio, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(jLabel8))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JTcodBusc, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JCbusInqu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(149, 149, 149)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JDfinal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(JTvendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addComponent(jLabel2)))
                .addGap(13, 13, 13)
                .addComponent(jLabel4)
                .addGap(219, 219, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(8, 8, 8)
                .addComponent(JTvendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JTcodBusc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JCpropiedades)
                    .addComponent(jButton1))
                .addGap(62, 62, 62)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JCinquilinos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(JCbusInqu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JDinicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JDfinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton10)
                    .addComponent(jButton4))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Subir Contrato", jPanel1);

        jLabel9.setText("Codigo de Contrato");

        jButton5.setText("Rescindir");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton8.setText("Salir");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(337, 337, 337)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel9))
                    .addComponent(JTcodRes, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(416, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel9)
                .addGap(14, 14, 14)
                .addComponent(JTcodRes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jButton5)
                .addGap(46, 46, 46)
                .addComponent(jButton8)
                .addContainerGap(351, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Rescindir Contrato", jPanel2);

        jLabel10.setText("Codigo Contrato");

        jButton6.setText("Renovar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Salir");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(302, 302, 302)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel10))
                    .addComponent(JTcodB, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton6)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jButton7))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(JCfin, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(386, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(JTcodB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(JCfin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(jButton6)
                .addGap(39, 39, 39)
                .addComponent(jButton7)
                .addContainerGap(254, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Renovar Contrato", jPanel3);

        jLabel11.setText("Buscar Contratos de Inquilino");

        JCinqui2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        JCinqui2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCinqui2ActionPerformed(evt);
            }
        });

        JBbusXinq.setText("Buscar");
        JBbusXinq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBbusXinqActionPerformed(evt);
            }
        });

        jLabel13.setText("Buscar Contratos de Propiedad");

        JBconXpropiedad.setText("Buscar");
        JBconXpropiedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBconXpropiedadActionPerformed(evt);
            }
        });

        jLabel15.setText("Buscar Contratos de propietario");

        JBbusXpropietario.setText("Buscar");
        JBbusXpropietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBbusXpropietarioActionPerformed(evt);
            }
        });

        JTcontratos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        JTcontratos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTcontratosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTcontratos);

        JRBvigente.setText("Vigentes");
        JRBvigente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRBvigenteActionPerformed(evt);
            }
        });

        JRBvencidos.setText("Vencidos");
        JRBvencidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRBvencidosActionPerformed(evt);
            }
        });

        jButton9.setText("Salir");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        JBlimpiar2.setText("Limpiar");
        JBlimpiar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBlimpiar2ActionPerformed(evt);
            }
        });

        jButton11.setText("Rescindir");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setText("Renovar");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jBImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Quickprinting_printing_6313.png"))); // NOI18N
        jBImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBImprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBImprimir, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                    .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(255, 255, 255)
                        .addComponent(JBlimpiar2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jButton11)
                        .addGap(49, 49, 49)
                        .addComponent(JRBvigente)
                        .addGap(78, 78, 78)
                        .addComponent(JRBvencidos)
                        .addGap(29, 29, 29)
                        .addComponent(jButton12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JDchoinegral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(10, 10, 10)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(JCinqui2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JCpropiedades2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JCpropietarios, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(53, 53, 53)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(JBbusXinq)
                                .addComponent(JBconXpropiedad)
                                .addComponent(JBbusXpropietario)))))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(JCinqui2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBbusXinq))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(JCpropiedades2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBconXpropiedad))
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JCpropietarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(JBbusXpropietario))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jBImprimir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton11)
                                .addComponent(jButton12))
                            .addComponent(JDchoinegral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JBlimpiar2)
                        .addGap(97, 97, 97))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JRBvigente)
                            .addComponent(JRBvencidos))
                        .addGap(160, 160, 160))))
        );

        jTabbedPane1.addTab("Buscar Contrato", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 883, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                Propiedad_Inmueble_Data proData = new Propiedad_Inmueble_Data(conexion);
                PropietarioData propie = new PropietarioData(conexion);
                Propiedad_Inmueble propi = proData.buscarInmPorCodigo(JTcodBusc.getText(),propie);
                JCpropiedades.setSelectedItem(propi);
                
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            InquilinoData inquiData = new InquilinoData(conexion);
            Inquilino inqui = inquiData.buscarInquilino(Long.parseLong(JCbusInqu.getText()));
            JCinquilinos.setSelectedItem(inqui);
            

// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
try{
        Date inicio = JDinicio.getDate();
ZoneId defaultZoneId = ZoneId.systemDefault();
Instant instant = inicio.toInstant();
LocalDate localInicio = instant
    .atZone(defaultZoneId).toLocalDate();

    Date fin = JDfinal.getDate();
ZoneId defaultZoneId2 = ZoneId.systemDefault();
Instant instant2 = fin.toInstant();
LocalDate localFinal = instant2
    .atZone(defaultZoneId).toLocalDate();
if(localFinal.isBefore(localInicio)){
      JOptionPane.showMessageDialog(this, "La fecha de finalizacion del contrato no puede ser anterior a la fecha de inicio del contrato");
}else{
        ContratoAlquilerData coAlData = new ContratoAlquilerData(conexion);
        ArrayList<ContratoAlquiler> contratosDelInmueble = coAlData.buscarContratosPorInmueble((Propiedad_Inmueble)JCpropiedades.getSelectedItem());
        boolean disponible = true;
        for (ContratoAlquiler contratoAlquiler : contratosDelInmueble) {
            if(localInicio.isBefore(contratoAlquiler.getFecha_Final().plusDays(1))){
            disponible = false;
            }
            
        }
        if(disponible){
            if(localInicio.isAfter(LocalDate.now())){
        ContratoAlquiler nuevoContrato = new ContratoAlquiler(JTvendedor.getText(),(Propiedad_Inmueble) JCpropiedades.getSelectedItem(), (Inquilino) JCinquilinos.getSelectedItem(), localInicio, localFinal);   
        
         System.out.println(nuevoContrato.getFecha_Inicio());
         System.out.println(nuevoContrato.getFecha_Final());
         coAlData.firmarContrato(nuevoContrato);
         limpiarRegistros();
        }
        else{
            JOptionPane.showMessageDialog(this, "La fecha de inicio del contrato no puede ser anterior a la fecha actual");
        }
        }else{
            JOptionPane.showMessageDialog(this, "El inmueble aun participa en otro contrato en la fecha de inicio seleccionada");
        }}
}catch(NullPointerException ex){
    JOptionPane.showMessageDialog(this, "Debe seleccionar las fechas de inicio y final del contrato");
}

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
            ContratoAlquilerData caData = new ContratoAlquilerData(conexion);
             ContratoAlquiler cont =  caData.buscarContrato(JTcodRes.getText());
             try {
                 caData.rescindirContrato(cont);
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(this, "El codigo no corresponde a un contrato vigente");
        }

// TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
         ContratoAlquilerData caData = new ContratoAlquilerData(conexion);
         ContratoAlquiler cont =  caData.buscarContrato(JTcodB.getText());
          Date nuFinal = JCfin.getDate();
          if(nuFinal==null){
           JOptionPane.showMessageDialog(this, "Debe seleccionar una fecha");
          }
          else{
          ZoneId defaultZoneId = ZoneId.systemDefault();
          Instant instant = nuFinal.toInstant();
          LocalDate localFinal = instant
                        .atZone(defaultZoneId).toLocalDate();
         try{
           caData.renovarContrato(cont, localFinal);
          
           limpiarRegistros();
         }catch(NullPointerException ex){
             JOptionPane.showMessageDialog(this, "El codigo no corresponde a ningun contrato");
          
         }
         
          }
         
// TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void JRBvencidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRBvencidosActionPerformed
         borraFilasTabla();
        if((JRBvencidos.isSelected()&& JRBvigente.isSelected()) ){
          for (ContratoAlquiler contrato : contratos) {
             modelo.addRow(new Object[]{contrato.getCodContrato(), contrato.getVendedor(), contrato.getPropiedad().getCodigo() , contrato.getInquilino().getDni(), contrato.getFecha_Inicio(), contrato.getFecha_Final()});
         }
         }
          else if(!JRBvencidos.isSelected()&& !JRBvigente.isSelected()){
              borraFilasTabla();
        }
         else if(JRBvencidos.isSelected()&& !JRBvigente.isSelected()){
             ArrayList<ContratoAlquiler> arrayAuxiliar = new ArrayList<>();
             for (ContratoAlquiler contrato : contratos) {
                 if(contrato.getFecha_Final().isBefore(LocalDate.now()))
                     arrayAuxiliar.add(contrato);
             }
              for (ContratoAlquiler contrato : arrayAuxiliar) {
             modelo.addRow(new Object[]{contrato.getCodContrato(), contrato.getVendedor(), contrato.getPropiedad().getCodigo() , contrato.getInquilino().getDni(), contrato.getFecha_Inicio(), contrato.getFecha_Final()});
         }
         }
         else if(!JRBvencidos.isSelected()&& JRBvigente.isSelected()){
             ArrayList<ContratoAlquiler> arrayAuxiliar = new ArrayList<>();
             for (ContratoAlquiler contrato : contratos) {
                 if((contrato.getFecha_Final().isAfter(LocalDate.now())|| contrato.getFecha_Final().isEqual(LocalDate.now()))){
                     arrayAuxiliar.add(contrato);
             }
             }
              for (ContratoAlquiler contrato : arrayAuxiliar) {
             modelo.addRow(new Object[]{contrato.getCodContrato(), contrato.getVendedor(), contrato.getPropiedad().getCodigo() , contrato.getInquilino().getDni(), contrato.getFecha_Inicio(), contrato.getFecha_Final()});
         }
         }        // TODO add your handling code here:
    }//GEN-LAST:event_JRBvencidosActionPerformed

    private void JCinqui2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCinqui2ActionPerformed
       
        
              // TODO add your handling code here:
    }//GEN-LAST:event_JCinqui2ActionPerformed

    ArrayList<ContratoAlquiler> contratos;
    
    private void JBbusXinqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBbusXinqActionPerformed
       borraFilasTabla();
        limpiarRegistros();
        ContratoAlquilerData contData = new ContratoAlquilerData(conexion);
      contratos = contData.mostrarContratosPorInquilino((Inquilino)JCinqui2.getSelectedItem());  
        for (ContratoAlquiler contrato : contratos) {
             modelo.addRow(new Object[]{contrato.getCodContrato(), contrato.getVendedor(), contrato.getPropiedad().getCodigo() , contrato.getInquilino().getDni(), contrato.getFecha_Inicio(), contrato.getFecha_Final()});
            
        }
           JRBvencidos.setSelected(true);
           JRBvigente.setSelected(true);
// TODO add your handling code here:
    }//GEN-LAST:event_JBbusXinqActionPerformed

    private void JBconXpropiedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBconXpropiedadActionPerformed
        borraFilasTabla();
        ContratoAlquilerData contData = new ContratoAlquilerData(conexion);
        contratos = contData.buscarContratosPorInmueble((Propiedad_Inmueble)JCpropiedades2.getSelectedItem());  
        for (ContratoAlquiler contrato : contratos) {
             modelo.addRow(new Object[]{contrato.getCodContrato(), contrato.getVendedor(), contrato.getPropiedad().getCodigo() , contrato.getInquilino().getDni(), contrato.getFecha_Inicio(), contrato.getFecha_Final()});
        // TODO add your handling code here:
    }//GEN-LAST:event_JBconXpropiedadActionPerformed
      JRBvencidos.setSelected(true);
           JRBvigente.setSelected(true);
    }
    private void JBbusXpropietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBbusXpropietarioActionPerformed
        borraFilasTabla();
        ContratoAlquilerData contData = new ContratoAlquilerData(conexion);
         contratos = contData.mostrarContratosPorPropietario((Propietario)JCpropietarios.getSelectedItem());  
        for (ContratoAlquiler contrato : contratos) {
             modelo.addRow(new Object[]{contrato.getCodContrato(), contrato.getVendedor(), contrato.getPropiedad().getCodigo() , contrato.getInquilino().getDni(), contrato.getFecha_Inicio(), contrato.getFecha_Final()});       // TODO add your handling code here:
    }//GEN-LAST:event_JBbusXpropietarioActionPerformed
       JRBvencidos.setSelected(true);
           JRBvigente.setSelected(true);
    }
    
    
    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
      dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        limpiarRegistros();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void JBlimpiar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBlimpiar2ActionPerformed
         limpiarRegistros();        // TODO add your handling code here:
    }//GEN-LAST:event_JBlimpiar2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
    dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void JRBvigenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRBvigenteActionPerformed
         borraFilasTabla();
        if((JRBvencidos.isSelected()&& JRBvigente.isSelected())){
          for (ContratoAlquiler contrato : contratos) {
             modelo.addRow(new Object[]{contrato.getCodContrato(), contrato.getVendedor(), contrato.getPropiedad().getCodigo() , contrato.getInquilino().getDni(), contrato.getFecha_Inicio(), contrato.getFecha_Final()});
         }
         }
        else if(!JRBvencidos.isSelected()&& !JRBvigente.isSelected()){
              borraFilasTabla();
        }
         else if(JRBvencidos.isSelected()&& !JRBvigente.isSelected()){
             ArrayList<ContratoAlquiler> arrayAuxiliar = new ArrayList<>();
             for (ContratoAlquiler contrato : contratos) {
                 if(contrato.getFecha_Final().isBefore(LocalDate.now()))
                     arrayAuxiliar.add(contrato);
             }
              for (ContratoAlquiler contrato : arrayAuxiliar) {
             modelo.addRow(new Object[]{contrato.getCodContrato(), contrato.getVendedor(), contrato.getPropiedad().getCodigo() , contrato.getInquilino().getDni(), contrato.getFecha_Inicio(), contrato.getFecha_Final()});
         }
         }
         else if(!JRBvencidos.isSelected()&& JRBvigente.isSelected()){
             ArrayList<ContratoAlquiler> arrayAuxiliar = new ArrayList<>();
             for (ContratoAlquiler contrato : contratos) {
                 if((contrato.getFecha_Final().isAfter(LocalDate.now())|| contrato.getFecha_Final().isEqual(LocalDate.now()))){
                     arrayAuxiliar.add(contrato);
             }
             }
              for (ContratoAlquiler contrato : arrayAuxiliar) {
             modelo.addRow(new Object[]{contrato.getCodContrato(), contrato.getVendedor(), contrato.getPropiedad().getCodigo() , contrato.getInquilino().getDni(), contrato.getFecha_Inicio(), contrato.getFecha_Final()});
         }
         }
             // TODO add your handling code here:
    }//GEN-LAST:event_JRBvigenteActionPerformed

     String alquilarRescindirDesdeTabla ="";
    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
           if(!alquilarRescindirDesdeTabla.equals("")){
               ContratoAlquilerData contData = new ContratoAlquilerData(conexion);
               contData.rescindirContrato(contData.buscarContrato(alquilarRescindirDesdeTabla));
               alquilarRescindirDesdeTabla="";
           }else{JOptionPane.showMessageDialog(this, "No ha seleccionado ningun contrato");}
           
    }//GEN-LAST:event_jButton11ActionPerformed

    private void JTcontratosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTcontratosMouseClicked
            alquilarRescindirDesdeTabla = (String)JTcontratos.getValueAt(JTcontratos.getSelectedRow(), 0);        // TODO add your handling code here:
    }//GEN-LAST:event_JTcontratosMouseClicked

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
         if(!alquilarRescindirDesdeTabla.equals("")){        
        ContratoAlquilerData caData = new ContratoAlquilerData(conexion);
         ContratoAlquiler cont =  caData.buscarContrato(alquilarRescindirDesdeTabla);
          Date nuFinal = JDchoinegral.getDate();
          if(nuFinal==null){
           JOptionPane.showMessageDialog(this, "Debe seleccionar una fecha");
          }
          else{
          ZoneId defaultZoneId = ZoneId.systemDefault();
          Instant instant = nuFinal.toInstant();
          LocalDate localFinal = instant
                        .atZone(defaultZoneId).toLocalDate();
          
         try{
               if(localFinal.isBefore(cont.getFecha_Final())){
           JOptionPane.showMessageDialog(this, "La renovacion no puede terminar antes que el contrato original");
         }   else{
           caData.renovarContrato(cont, localFinal);
         
           alquilarRescindirDesdeTabla ="";
           limpiarRegistros();
               }
         }catch(NullPointerException ex){
             JOptionPane.showMessageDialog(this, "El codigo no corresponde a ningun contrato");
          
         } 
          }
         }else{JOptionPane.showMessageDialog(this, "No ha seleccionado ningun contrato");}
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jBImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBImprimirActionPerformed
        // TODO add your handling code here:
         Inquilino inq =(Inquilino)JCinqui2.getSelectedItem();
      Propiedad_Inmueble p_Inmu = (Propiedad_Inmueble)JCpropiedades2.getSelectedItem();
      Propietario prop =(Propietario)JCpropietarios.getSelectedItem();  
       Document documento = new Document();
       
        try {
            String ruta = System.getProperty("user.home");
            PdfWriter.getInstance(documento, new FileOutputStream(ruta + "/Desktop/" + prop.getNombrePropietario().trim()+".pdf"));
            
           com.itextpdf.text.Image header = com.itextpdf.text.Image.getInstance("src/image/BannerPDF.jpg");
           header.scaleToFit(650,1000);
           header.setAlignment(Chunk.ALIGN_CENTER);
           
            Paragraph parrafo = new Paragraph();
            parrafo.setAlignment(Paragraph.ALIGN_CENTER);
            parrafo.add("información Del Cliente. \n \n");
            parrafo.setFont(FontFactory.getFont("Tahoma", 14, Font.BOLD, BaseColor.DARK_GRAY));
            
            documento.open();
            documento.add(header);
            documento.add(parrafo);
            
           PdfPTable tablaCliente = new PdfPTable(4);
            tablaCliente.addCell("CodigoInterno");
            tablaCliente.addCell("Nombre");
            tablaCliente.addCell("Apellido");
            tablaCliente.addCell("Dni");
            
            tablaCliente.addCell(inq.getIdInquilino()+"");
            tablaCliente.addCell(inq.getNombre());
            tablaCliente.addCell(inq.getApellido());
            tablaCliente.addCell(inq.getDni()+"");
            documento.add(tablaCliente);
            
            Paragraph parrafo2 = new Paragraph();
            parrafo2.setAlignment(Paragraph.ALIGN_CENTER);
            parrafo2.add("\n \n información Del Propietario \n\n");
            parrafo2.setFont(FontFactory.getFont("Tahoma",14,Font.BOLD, BaseColor.DARK_GRAY));
            documento.add(parrafo2); 
            
            PdfPTable tablaPropietario = new PdfPTable(4);
            tablaPropietario.addCell("CodigoInterno");
            tablaPropietario.addCell("Nombre");
            tablaPropietario.addCell("Apellido");
            tablaPropietario.addCell("Dni"); 
            
            tablaPropietario.addCell(prop.getIdPropietario()+"");
            tablaPropietario.addCell(prop.getNombrePropietario());
            tablaPropietario.addCell(prop.getApellidoPropietario());
            tablaPropietario.addCell(prop.getDNI()+"");            
            documento.add(tablaPropietario);
            
             Paragraph parrafo3 = new Paragraph();
            parrafo3.setAlignment(Paragraph.ALIGN_CENTER);
            parrafo3.add("\n \n información De Propiedades \n\n");
            parrafo3.setFont(FontFactory.getFont("Tahoma",14,Font.BOLD, BaseColor.DARK_GRAY));
            documento.add(parrafo3); 
            
            PdfPTable tablaContratos = new PdfPTable(6);
            tablaContratos.addCell("cod");
            tablaContratos.addCell("Vendedor");           
            tablaContratos.addCell("codPropiedad");    
            tablaContratos.addCell("DniCliente"); 
            tablaContratos.addCell("F.Inicio");
            tablaContratos.addCell("F.Final");
            
            for (ContratoAlquiler contrato : contratos) {
                
            if(contrato.getInquilino().getIdInquilino()== inq.getIdInquilino() && contrato.getPropiedad().getIdPropiedad()== p_Inmu.getIdPropiedad()){
            tablaContratos.addCell(contrato.getCodContrato());
            tablaContratos.addCell(contrato.getVendedor());
            tablaContratos.addCell(contrato.getPropiedad().getCodigo());
            tablaContratos.addCell(contrato.getInquilino().getDni()+"");
            tablaContratos.addCell(contrato.getFecha_Inicio()+"");
            tablaContratos.addCell(contrato.getFecha_Final()+"");   
            
           }
        }  
        documento.add(tablaContratos);    
        JOptionPane.showMessageDialog(this,"El documento se encuentra en Escritorio");
          documento.close();     
            
        } catch (Exception e) {
        JOptionPane.showMessageDialog(this,"Error al imprimir el documeto");    
        }
        
    }//GEN-LAST:event_jBImprimirActionPerformed

    public void setJTcodBusc(JTextField JTcodBusc) {
        this.JTcodBusc = JTcodBusc;
    }

    public JTextField getJTcodBusc() {
        return JTcodBusc;
    }

    public JComboBox<Propiedad_Inmueble> getJCpropiedades() {
        return JCpropiedades;
    }

    public void setJCpropiedades(JComboBox<Propiedad_Inmueble> JCpropiedades) {
        this.JCpropiedades = JCpropiedades;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBbusXinq;
    private javax.swing.JButton JBbusXpropietario;
    private javax.swing.JButton JBconXpropiedad;
    private javax.swing.JButton JBlimpiar2;
    private javax.swing.JTextField JCbusInqu;
    private com.toedter.calendar.JDateChooser JCfin;
    private javax.swing.JComboBox<Inquilino> JCinqui2;
    private javax.swing.JComboBox<Inquilino> JCinquilinos;
    private javax.swing.JComboBox<Propiedad_Inmueble> JCpropiedades;
    private javax.swing.JComboBox<Propiedad_Inmueble> JCpropiedades2;
    private javax.swing.JComboBox<Propietario> JCpropietarios;
    private com.toedter.calendar.JDateChooser JDchoinegral;
    private com.toedter.calendar.JDateChooser JDfinal;
    private com.toedter.calendar.JDateChooser JDinicio;
    private javax.swing.JRadioButton JRBvencidos;
    private javax.swing.JRadioButton JRBvigente;
    private javax.swing.JTextField JTcodB;
    private javax.swing.JTextField JTcodBusc;
    private javax.swing.JTextField JTcodRes;
    private javax.swing.JTable JTcontratos;
    private javax.swing.JTextField JTvendedor;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JButton jBImprimir;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
